/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.batalha;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author CMU
 */
public class PanelCelulaAgua extends javax.swing.JPanel {

    private boolean shot;
    private boolean checkNavio;
    private final int id;
    private ImageIcon icon;

    public int getId() {
        return id;
    }

    /**
     * Creates new form PanelCelulaAgua
     *
     * @param id
     */
    public PanelCelulaAgua(int id) {
        this.id = id;
        initComponents();
        setOpaque(false);
        shot = false;
        checkNavio = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblState = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(50, 50));
        setPreferredSize(new java.awt.Dimension(50, 50));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lblState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblState, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblState, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        mouseEntered();
    }//GEN-LAST:event_formMouseEntered

    public void mouseEntered(){
        if (!getShot()) {
            setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 1));
        }
    }
    
    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        mouseExited();
    }//GEN-LAST:event_formMouseExited

    public void mouseExited(){
//        System.out.println("Mouse saiu");
        if (!getShot()) {
            setBorder(null);
        }
    }
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mousePressed();
    }//GEN-LAST:event_formMousePressed

    public void mousePressed(){
        System.out.println("Click na celula de id: " + id);
        if (!getShot()) {
            shot = true;
            setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 51, 4), 1));
            if (checkNavio) {
                icon = new ImageIcon(getClass().getResource("/img/explosion.png"));
                icon.setImage(icon.getImage().getScaledInstance(this.getWidth(), this.getHeight(), 100));
                lblState.setIcon(icon);
            } else {
                lblState.setText("X");
            }
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        if (shot) {
            g.setColor(new Color(52, 51, 4, 100));
            g.fillRect(0, 0, getWidth(), getHeight());
        }
    }

    public boolean getShot() {
        return shot;
    }

    public boolean getCheckNavio() {
        return checkNavio;
    }

    public void setCheckNavio(boolean checkNavio) {
        this.checkNavio = checkNavio;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblState;
    // End of variables declaration//GEN-END:variables
}
