package core.batalha;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author CMU
 */
public class PanelNavioStatus extends javax.swing.JPanel {

    javax.swing.JLabel[] lblExplosao;
    int sizeImage = 40;
    
    /**
     * Creates new form PanelNavioStatus
     *
     * @param porteNavio
     */
    public PanelNavioStatus(int porteNavio) {
        initComponents();
        initConfig(porteNavio);
    }
    
    public PanelNavioStatus(int porteNavio, int sizeImage) {
        initComponents();
        this.sizeImage = sizeImage;
        initConfig(porteNavio);
    }
    
    public void initConfig(int porteNavio){
        lblExplosao = new javax.swing.JLabel[porteNavio];
        for(int x = 0; x < porteNavio; x++){
            lblExplosao[x] = new javax.swing.JLabel();
            add(lblExplosao[x], new org.netbeans.lib.awtextra.AbsoluteConstraints(sizeImage * x, 0, sizeImage, sizeImage));
        }
        
        // cria o Label que armazena a imagem do navio
        javax.swing.JLabel lblIconNavio = new javax.swing.JLabel();
        
        // seleciona a imagem/tamanho do navio com o parametro passado no construtor
        ImageIcon icon = null;
        switch(porteNavio){
            case 1:
                icon = new ImageIcon(getClass().getResource("/img/embarcacoes/submarino.png"));
                break;
                
            case 2:
                icon = new ImageIcon(getClass().getResource("/img/embarcacoes/navio_2.png"));
                break;
                
            case 3:
                icon = new ImageIcon(getClass().getResource("/img/embarcacoes/navio_3.png"));
                break;
                
            case 4:
                icon = new ImageIcon(getClass().getResource("/img/embarcacoes/navio_4.png"));
                break;
                
            case 5:
                icon = new ImageIcon(getClass().getResource("/img/embarcacoes/navio_5.png"));
                break;
        }
        icon.setImage(icon.getImage().getScaledInstance(sizeImage * porteNavio, sizeImage, 100));
        lblIconNavio.setIcon(icon);
        lblIconNavio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblIconNavio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, sizeImage == 40 ? 200 : 100, sizeImage));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents

    void setExplosion(int index) {
        ImageIcon iconExplosao = new javax.swing.ImageIcon(getClass().getResource("/img/explosion.png"));
        iconExplosao.setImage(iconExplosao.getImage().getScaledInstance(sizeImage, sizeImage, 100));
        lblExplosao[index].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExplosao[index].setIcon(iconExplosao);
//        lblExplosao[index].setText("X");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
